In [1]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv")
csv_1

,id,first_name,last_name,email,gender,ip_address,Unnamed: 6
0,1,Bertie,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN
1,2,Kandy,Boddice,kboddice1@ucsd.edu,Female,35.67.128.130,NaN
2,3,Nomi,Currey,ncurrey2@macromedia.com,Female,140.147.23.6,NaN
3,4,Arlyn,Duny,aduny3@usatoday.com,Female,170.76.10.213,NaN
4,5,Claretta,Byrne,cbyrne4@ted.com,Female,233.17.46.173,NaN
...,...,...,...,...,...,...,...
995,996,Julianne,Gaze,jgazern@bravesites.com,Female,59.21.158.117,NaN
996,997,Brittni,L'Hommee,blhommeero@nationalgeographic.com,Female,90.46.64.186,NaN
997,998,Alyss,Chapling,achaplingrp@arstechnica.com,Female,106.86.250.186,NaN
998,999,Danya,Rahl,drahlrq@google.co.jp,Male,183.178.226.211,NaN
999,1000,Tania,Love,tloverr@feedburner.com,Female,72.13.42.216,NaN

In [2]:
csv_2=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",nrows=1)
csv_2

,id,first_name,last_name,email,gender,ip_address,Unnamed: 6
0,1,Bertie,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN

In [3]:
csv_3=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",nrows=3)
csv_3

,id,first_name,last_name,email,gender,ip_address,Unnamed: 6
0,1,Bertie,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN
1,2,Kandy,Boddice,kboddice1@ucsd.edu,Female,35.67.128.130,NaN
2,3,Nomi,Currey,ncurrey2@macromedia.com,Female,140.147.23.6,NaN

In [5]:
csv_4=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",usecols=["last_name","email"])
csv_4

    last_name                              email
0     Brinded                  bbrinded0@ihg.com
1     Boddice                 kboddice1@ucsd.edu
2      Currey            ncurrey2@macromedia.com
3        Duny                aduny3@usatoday.com
4       Byrne                    cbyrne4@ted.com
..        ...                                ...
995      Gaze             jgazern@bravesites.com
996  L'Hommee  blhommeero@nationalgeographic.com
997  Chapling        achaplingrp@arstechnica.com
998      Rahl               drahlrq@google.co.jp
999      Love             tloverr@feedburner.com

[1000 rows x 2 columns]

In [9]:
csv_5=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",skiprows=[2])
csv_5

,id,first_name,last_name,email,gender,ip_address,Unnamed: 6
0,1,Bertie,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN
1,3,Nomi,Currey,ncurrey2@macromedia.com,Female,140.147.23.6,NaN
2,4,Arlyn,Duny,aduny3@usatoday.com,Female,170.76.10.213,NaN
3,5,Claretta,Byrne,cbyrne4@ted.com,Female,233.17.46.173,NaN
4,6,Rene,Srawley,rsrawley5@deliciousdays.com,Female,236.59.93.169,NaN
...,...,...,...,...,...,...,...
994,996,Julianne,Gaze,jgazern@bravesites.com,Female,59.21.158.117,NaN
995,997,Brittni,L'Hommee,blhommeero@nationalgeographic.com,Female,90.46.64.186,NaN
996,998,Alyss,Chapling,achaplingrp@arstechnica.com,Female,106.86.250.186,NaN
997,999,Danya,Rahl,drahlrq@google.co.jp,Male,183.178.226.211,NaN
998,1000,Tania,Love,tloverr@feedburner.com,Female,72.13.42.216,NaN

In [10]:
csv_4=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",index_col="first_name")
csv_4

,id,last_name,email,gender,ip_address,Unnamed: 6
first_name,,,,,,
Bertie,1,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN
Kandy,2,Boddice,kboddice1@ucsd.edu,Female,35.67.128.130,NaN
Nomi,3,Currey,ncurrey2@macromedia.com,Female,140.147.23.6,NaN
Arlyn,4,Duny,aduny3@usatoday.com,Female,170.76.10.213,NaN
Claretta,5,Byrne,cbyrne4@ted.com,Female,233.17.46.173,NaN
...,...,...,...,...,...,...
Julianne,996,Gaze,jgazern@bravesites.com,Female,59.21.158.117,NaN
Brittni,997,L'Hommee,blhommeero@nationalgeographic.com,Female,90.46.64.186,NaN
Alyss,998,Chapling,achaplingrp@arstechnica.com,Female,106.86.250.186,NaN
Danya,999,Rahl,drahlrq@google.co.jp,Male,183.178.226.211,NaN
Tania,1000,Love,tloverr@feedburner.com,Female,72.13.42.216,NaN

In [12]:
csv_5=pd.read_csv("C:\\Users\\suren\\Downloads\\MOCK_DATA.csv",index_col="first_name",dtype={"id":"float"})
csv_5

,id,last_name,email,gender,ip_address,Unnamed: 6
first_name,,,,,,
Bertie,1.0,Brinded,bbrinded0@ihg.com,Female,148.15.130.67,NaN
Kandy,2.0,Boddice,kboddice1@ucsd.edu,Female,35.67.128.130,NaN
Nomi,3.0,Currey,ncurrey2@macromedia.com,Female,140.147.23.6,NaN
Arlyn,4.0,Duny,aduny3@usatoday.com,Female,170.76.10.213,NaN
Claretta,5.0,Byrne,cbyrne4@ted.com,Female,233.17.46.173,NaN
...,...,...,...,...,...,...
Julianne,996.0,Gaze,jgazern@bravesites.com,Female,59.21.158.117,NaN
Brittni,997.0,L'Hommee,blhommeero@nationalgeographic.com,Female,90.46.64.186,NaN
Alyss,998.0,Chapling,achaplingrp@arstechnica.com,Female,106.86.250.186,NaN
Danya,999.0,Rahl,drahlrq@google.co.jp,Male,183.178.226.211,NaN
Tania,1000.0,Love,tloverr@feedburner.com,Female,72.13.42.216,NaN